### ISSUE TITLE
How do we use the balances pallet instead of the system pallet to store the balances

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#118]
If we take a look at the polkadot js documentation we can see the following note:
This is only used in the case that this pallet is used to store balances.
Now how do we use the balances pallet to store the balances? because we also have the ```api.query.system.account``` function instead of ```api.query.balances.account```

**Comment by shawntabrizi** [comment]
@noahsalvadordenjo hey Noah, that was my bad. I put `Balances` because I assumed the pallet automatically handled it, but it doesn't. I have updated the sample in the StackOveflow post to be correct:

https://stackoverflow.com/questions/66511734/how-do-we-use-the-balances-pallet-instead-of-the-system-pallet-to-store-the-bala/66512980

I have tested it locally.
