### ISSUE TITLE
Kusama v0.9.0 Types

### ISSUE THREAD

**Issue by danforbes** [paritytech/subport#163]
I would like to run the Front-End Template against a local development instance of Kusama v0.9.0. What is the most straightforward way to acquire/generate the necessary type definitions?

**Comment by shawntabrizi** [comment]
Types need to be manually tracked between the Substrate runtime and the JavaScript libraries.

This is maintained by Polkadot JS and Jaco. If the Pokadot JS Apps works, then the front-end template will work. You might just need to bump the Polkadot JS dependencies in the front-end template like:

```
yarn add @polkadot/api
```

Otherwise, for any missing types, you will need to look in the Substrate / Polkadot repository for that type definition.

This problem in general will be solved by: https://github.com/paritytech/substrate/issues/917

**Comment by danforbes** [comment]
Running `yarn up @polkadot/*` solved the issue. It would be nice for the maintainers of chains like Kusama and Polkadot to also maintain the types necessary for people to interact with those chains.
