### ISSUE TITLE
pallet-assets: fungibles trait implementation type error

### ISSUE THREAD

**Issue by KingFishDev** [paritytech/subport#167]
When attempting to use a loose coupling of pallet-assets' fungibles trait implementation, there is an error when to pass in the correct `AssetId` and `BalanceId`. I've spoken with @shawntabrizi and he mentioned adding `+ RuntimeDebug` to where the traits are [defined](https://github.com/paritytech/substrate/blob/master/frame/support/src/traits/tokens/misc.rs#L162) may fix the problem
![image](https://user-images.githubusercontent.com/74088151/118184204-11b96480-b409-11eb-97c0-32f89b2f2601.png)

**Comment by ayushmishra2005** [comment]
@KingFishDev Can you mention sample code snippet?

**Comment by shawntabrizi** [comment]
@KingFishDev this will be solved with this PR: https://github.com/paritytech/substrate/pull/8476/files#diff-bec50fd168cec24e82b4e8915a318da459c30b4715862cb0bb7693931501d4b2R206

you can see the fix is very simple and you are welcome to make a PR to add this yourself ahead of time:

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/1860335/118408174-55eb7580-b652-11eb-8fc8-8c780abb74b4.png">

**Comment by KingFishDev** [comment]
@shawntabrizi related: [PR](https://github.com/paritytech/substrate/pull/8830)

**Comment by NukeManDan** [comment]
Checking in here guys: I see the first PR is still open, but your PR is merged @KingFishDev  🎉 - is this ready to close?

**Comment by shawntabrizi** [comment]
yes we can close it, but he needs to wait for the next node-template release to use it, or do it himself
