### ISSUE TITLE
[question] Produce blocks without aura, grandpa manual-seal rpc

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#20]
After you've removed aura and grandpa is there a way to produce a block from your runtime without using the manual-seal rpc? Wich traits do i have to implement?

**Comment by JoshOrndorff** [comment]
In order to produce blocks you need _some_ block authoring engine. Aura is one option, but since you've removed it I'm guessing you want something else. The options included with Substrate are

* Aura
* Babe
* Proof Of Work
  * Rustdocs https://crates.parity.io/sc_consensus_pow/index.html
  * Recipe https://substrate.dev/recipes/3-entrees/basic-pow.html
* Manual Seal
  * Rustdocs https://crates.parity.io/sc_consensus_manual_seal/index.html
  * Recipe https://substrate.dev/recipes/3-entrees/manual-seal.html
* Instant Seal
  * Recipe https://substrate.dev/recipes/3-entrees/kitchen-node.html

Of course you may also write your own authoring engine as well. If you want to do that, look at the ones I just mentioned as examples. But unless you're doing consensus research, you probably want to choose one of the already written options rather than write your own.
