### ISSUE TITLE
How to convert sp_consensus_aura::sr25519::app_sr25519::Public to AccountId

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#22]
Here's how i implement my sessionconfig 
```
		pallet_session: Some(SessionConfig {
			keys: initial_authorities.iter().map(|x| {
				(x.0.clone(), x.0.clone(), session_keys(
					x.0.clone(),
					x.1.clone(),
				))
			}).collect::<Vec<_>>(),
		}),
```
and here's my error
```
mismatched types
   --> node/src/chain_spec.rs:130:10
    |
130 |               keys: initial_authorities.iter().map(|x| {
    |  ___________________^
131 | |                 (x.0.clone(), x.0.clone(), session_keys(
132 | |                     x.0.clone(),
133 | |                     x.1.clone(),
134 | |                 ))
135 | |             }).collect::<Vec<_>>(),
    | |__________________________________^ expected struct `sp_core::crypto::AccountId32`, found struct `sp_consensus_aura::sr25519::app_sr25519::Public`
    |
    = note: expected struct `std::vec::Vec<(sp_core::crypto::AccountId32, sp_core::crypto::AccountId32, node_template_runtime::opaque::SessionKeys)>`
               found struct `std::vec::Vec<(sp_consensus_aura::sr25519::app_sr25519::Public, sp_consensus_aura::sr25519::app_sr25519::Public, node_template_runtime::opaque::SessionKeys)>`

error: aborting due to previous error
```
Heres how the main node implements it
```
	pallet_session: Some(SessionConfig {
			keys: initial_authorities.iter().map(|x| {
				(x.0.clone(), x.0.clone(), session_keys(
					x.2.clone(),
					x.3.clone(),
					x.4.clone(),
					x.5.clone(),
				))
			}).collect::<Vec<_>>(),
		}),
```
https://github.com/noahsalvadordenjo/sub

**Comment by JoshOrndorff** [comment]
@noahsalvadordenjo I've opened a PR against your repo to solve this issue https://github.com/noahsalvadordenjo/sub/pull/1 It will be worth the time to understand what was wrong before, and if it isn't clear I'll be happy to discuss it more.

---

When you manage your authorities directly with the aura and grandpa pallets like the unmodified node template does, you are managing the set of keys that nodes will actually sign blocks with. This is a very simple approach and it has all the usual benefits and drawbacks of simplicity. It's easy to understand and requires little code. But it isn't very flexable, and requires validators to protect their keys for long periods of time with no way to recover when they make a mistake.

When you choose to use the session pallet, you're choosing to think of the validators as set of ValidatorIds. A ValidatorId is a long-lasting "name" for a validator. In this code you have chosen to use a regular old AccountId as your ValidatorId. This is a reasonable and normal choice.

The sessions pallet allows you to associate the actual keys validators use to sign blocks, called "session keys", with these long-lives ValidatorIds. It also allows validators to rotate the their keys whenever they like. The problem is that you were trying to use one of the session keys (specifically the aura key) where the AccountId was required.

This whole thing is further complicated by the fact that both the aura key and the AccountId use sr25519 crypto. So bit-wise they are exactly the same key. However, Rust;s type-checker know that in general this may not be the case, and insist that you specify a properly-typed AccountId.

**Comment by noahsalvadordenjo** [comment]
Your update gives me the following error when i run the chain.
```
Thread 'main' panicked at 'Empty validator set for session 0 in genesis block!', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/macros.rs:13
```
How do i solve this?
