### ISSUE TITLE
Dev network has 0 balance for all accounts (s390x architecture)

### ISSUE THREAD

**Issue by mrihn** [paritytech/subport#235]
I started a local testnet with the following command:

polkadot --alice -d /tmp/alice --ws-external --rpc-external --rpc-cors all --dev

The node came up and is running without errors. I am able to connect to it with the browser UI, but all of the accounts (ALICE, ALICE_STASH, BOB, etc.) have a balance of 0.

The same thing happened when I brought up a "Local Two-node Testnet" as described in the README.

Is there a separate command (or command line option) to start the accounts with a certain amount of funds?

I am running with Polkadot version 0.9.9

**Comment by NukeManDan** [comment]
I have built and am running the [`release-0.9.9` build](https://github.com/paritytech/polkadot/tree/release-v0.9.9) and connected to apps UI to the default ws (https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/accounts) :
 
![image](https://user-images.githubusercontent.com/35669742/132430191-05245748-cb15-4dab-b5d1-b919697c0b78.png)

```
Development
polkadot/9090
---
Parity Polkadot
 v0.9.9
api v5.8.4-1
apps v0.95.2-103
```

Under the JS tab examples the `get system information` one yields:
```
You are connected to chain Development
You are using: Parity Polkadot v0.9.9-5af7db189-x86_64-linux-gnu
Node specific properties:
ss58Format 
tokenDecimals 
tokenSymbol 
```

Can you verify that you are indeed connecting to the right node and using the same (or otherwise what) versions?

**Comment by mrihn** [comment]
The `get system information` command shows the following:

```
You are connected to chain Development
You are using: Parity Polkadot v0.9.9-ccfd5b911-s390x-linux-gnu
Node specific properties:
ss58Format 
tokenDecimals 
tokenSymbol 
```

This node was built on s390x architecture. That should be the only difference.

**Comment by shawntabrizi** [comment]
@mrihn show a screenshot of what you are looking at

**Comment by mrihn** [comment]
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/88684821/132436306-bacda53f-aa1e-445e-8314-2130e6bb64bf.png">

**Comment by NukeManDan** [comment]
`You are using: Parity Polkadot v0.9.9-ccfd5b911-s390x-linux-gnu` [this commit](https://github.com/paritytech/polkadot/commit/ccfd5b911acbbf9ee3bcf75735bf2c44e24a60c6) -- It's actually much newer than the one [I am using](https://github.com/paritytech/polkadot/commit/5af7db1894a38ca08e2cd19fd522a229c88646a2)

Notice you are also on the 9100 runtime (top left). I suspect that this is a type issue that isn't covered in the version of the apps / api that you have. You could try the [binary in the release](https://github.com/paritytech/polkadot/releases/tag/v0.9.9) or I can try and track down the custom type mapping for you if it's critical that you use the present version.

**Comment by mrihn** [comment]
Thank you. That would be helpful if you find the custom type mapping for us. It is important that we use this version for our purposes.

**Comment by shawntabrizi** [comment]
unable to reproduce the issue

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/1860335/132545674-fc89a252-4375-47ad-b289-8f0813b20e62.png">


You need to be more specific here for us to help you, or provide some kind of docker image or something to reproduce.

**Comment by mrihn** [comment]
The issue seems to be related to the s390x architecture that I am using. When I replicate the scenario on x86, I also see the 10,000 unit account balances, but on s390x I see this:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/88684821/132571298-a140944e-65af-40fb-a743-58e3d30effa3.png">

Everything seems to be functional, aside from the accounts having a 0 balance. Is there any way to manually specify a non-zero account balance when the accounts are not automatically funded the 10,000 units?

**Comment by NukeManDan** [comment]
I don't see how they could be based on the target architecture.

Can you verify that balances are indeed 0 or if this is just a UI issue?
For example, you can use this to read the validator balances: https://polkadot.js.org/docs/api/examples/promise/read-storage
It _may_ be as simple as trying the example in the `js` tab of the UI (https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/js) and the `retrieve historical query data`, or this snippet in the UI's console:

```
// This example set shows how to make queries at a point
const ALICE = '5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY';

// retrieve the balance, once-off at the latest block
const { data: { free } } = await api.query.system.account(ALICE);

console.log('Alice has a current balance of', free.toHuman());
```

**Comment by mrihn** [comment]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/88684821/132746539-59f2f42b-4937-4dd5-bd3e-6783c9428c6d.png">

retrieve historical query data also shows a balance of 0

**Comment by mrihn** [comment]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/88684821/132760142-b67618b0-e4fa-48ae-85fa-68ba413907d5.png">

I tried the `Get chain state information` example with the alice node up and running
(`polkadot/target/release/polkadot --alice -d /tmp/alice --ws-external --rpc-external --rpc-cors all --dev`)

This response seems to indicate that the UI doesn't even recognize that the node is up (and also can't print the date for some reason).

**Comment by NukeManDan** [comment]
Was there any resolution for this @mrihn ? I am closing here as the issue is stale, please let me know if you did solve this :pray:

**Comment by vishwabmc** [comment]
Hello, this issue has not been resolved for s390x architecture. Recently, we built and tested https://github.com/substrate-developer-hub/substrate-node-template/ and ran into same issue.

NOTE: Since s390x is a Big Endian architecture, we ran into an issue when polkadot pulled in Merlin as a dependency.
https://github.com/dalek-cryptography/merlin/issues/58

For now, we went ahead by commenting the code  https://github.com/dalek-cryptography/merlin/blob/master/src/lib.rs#L9

/*
   |
10 | / compile_error!(
11 | |     r#"
12 | | This crate doesn't support big-endian targets, since I didn't
13 | | have one to test correctness on.  If you're seeing this message,
14 | | please file an issue!
15 | | "#
16 | | );
   | |__^
*/

Is this the reason why the balance is coming as zero ?
