### ISSUE TITLE
How to process rewards for crowdloan

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#281]
@al3mart As you suggested here https://github.com/paritytech/subport/issues/279#issuecomment-973042426, I tried to test crowdloan concept on local. 

I followed this https://docs.substrate.io/tutorials/v3/cumulus/start-relay/ to start relay chain and parachain on local. I connect parachain with relaychain.

After that, I used `Add Fund` from `Crowdloan` section to start crowdloan after following this https://wiki.polkadot.network/docs/learn-crowdloans#starting-a-crowdloan-campaign. Crowdloan was completed but nothing else happened. Neither its won nor lost.

![image](https://user-images.githubusercontent.com/1575561/142819924-c6c7ead7-f23f-46d5-b4e8-3c407a22556f.png)

I just wanted to know how to process the reward after successful crowdloan, if it won the slot? 

Also please let me know how to start auction on local relaychain?
This option is disabled on local relaychain

![image](https://user-images.githubusercontent.com/1575561/142820409-876ee3db-a280-40c5-916e-a54a98c552fb.png)

**Comment by al3mart** [comment]
In your example that crowdloan is on for slots `310 - 317`, there should be an auction (at least schheduled) going on for those two slots. In order to open one you just need to call [`new_auction`](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/auctions.rs#L253).

 When the auction is finished that para will be assigned the slots that has won. Upon arrival of that slot the para will onboard as a parachain and  start producing blocks.

When you mean reward after successful crowdloan, I guess you are talking about incentives for supporters ? There is nothing like that coded into the crowdloan code nor in the auctions one.
Incentivize is completely up to the teams to decide and definitely not mandatory. So it is your decision if doing so and how to implement it.

**Comment by ayushmishra2005** [comment]
Hi @al3mart Yes, I am talking about incentives for crowdloan contributors. 

Does it mean that team has to built their own reward application for this functionality? If yes, how would we get contributor data.

**Comment by al3mart** [comment]
Related to this, you might find [vesting pallet](https://github.com/paritytech/substrate/tree/master/frame/vesting) very interesting
