### ISSUE TITLE
Helixstreet Parachain ( later parathread )

### ISSUE THREAD

**Issue by helixstreet** [paritytech/subport#386]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

helixstreet.io

### Parachain Name

helixstreet

### ParaID

3025

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-2000-genesis.txt](https://github.com/paritytech/subport/files/8854666/para-2000-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-2000-wasm.txt](https://github.com/paritytech/subport/files/8854673/para-2000-wasm.txt)

### Anything else we should know?

for educational purpose only i am just trying to start a parachain ( to start later a parathread )

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
You should register your parathread before getting a slot.

**Comment by helixstreet** [comment]
Hi, thx for the reply.  
Sorry i missed that point. I hope i did it know correctly. The slot (Slot Number 3025 ) is (now) in the state "onboarding". The collator on my side is started; just the name Arctic confuses me.

**Comment by al3mart** [comment]
Right, is due to some historical reasons, some at some point it looks like Rococo had that team onboarded with that paraId.
Feel free to open a pr at [polkadot-js/apps](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/testingRelayRococo.ts#L18-L25) and amend that so it shows the correct information.

About your slot, I will be assigning you now, it looks like you should get onboarded as parachain at the next rotation of temp slots.

**Comment by helixstreet** [comment]
Awesome! Thx indeed - the docs are incredible good!
