### ISSUE TITLE
Is there any tutorial to integrate pallet_treasury in substrate2.0?

### ISSUE THREAD

**Issue by sbhm2** [paritytech/subport#45]
I am new to rust and substrate. I need to use treasury pallet. Is there any good tutorial available to integrate treasury_pallet in the substrate2.0 chain developed using [https://github.com/substrate-developer-hub/substrate-node-template](url).
I have followed the treasury_pallet docs but unable to fully understand it.

**Comment by danforbes** [comment]
We do not maintain such a guide because the steps will be different in each case. You can refer to the runtime of the demonstration node to see one example of adding the Treasury pallet to a runtime https://github.com/paritytech/substrate/blob/v2.0.0/bin/node/runtime/src/lib.rs#L608 The Polkadot runtime is another such example https://github.com/paritytech/polkadot/blob/v0.8.25/runtime/polkadot/src/lib.rs#L560 In general, what you need to do is configure the types specified by the `trait Trait` of the Treasury pallet https://substrate.dev/rustdocs/v2.0.0/pallet_treasury/trait.Trait.html Please let us know if you have any specific follow-up questions. If not, can you please close this Issue?

**Comment by sbhm2** [comment]
Thanks, @danforbes for giving out these links. Is there any resource to demonstrate the interaction of this treasury_pallet with a node application?

**Comment by danforbes** [comment]
You can refer to the Polkadot node to see how it uses the Treasury pallet. Here are some examples:
- Fees: https://github.com/paritytech/polkadot/blob/v0.8.25/runtime/polkadot/src/lib.rs#L230
- Staking: https://github.com/paritytech/polkadot/blob/v0.8.25/runtime/polkadot/src/lib.rs#L353

Also, I did not mention this before, but if you haven't already seen the basic [Add a Pallet tutorial](https://substrate.dev/docs/en/tutorials/add-a-pallet/) that will be a good place to learn about configuring the types specified by the `trait Trait` as I mentioned in my first comment.

**Comment by sbhm2** [comment]
Thanks, I'll look into it. I have gone through that tutorial but felt that tutorial doesn't deal much with Treasury pallet, so I had to create this issue.
