### ISSUE TITLE
curl https://getsubstrate.io -sSf | bash -s -- --fast aborts due to error

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#6]
```
info: retrying renaming '/home/noone/.rustup/tmp/svj00w7loxze4ljh_dir/rust-docs/share/doc/rust/html' to '/home/noone/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html'
info: retrying renaming '/home/noone/.rustup/tmp/svj00w7loxze4ljh_dir/rust-docs/share/doc/rust/html' to '/home/noone/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html'
info: rolling back changes
error: could not rename component file from '/home/noone/.rustup/tmp/svj00w7loxze4ljh_dir/rust-docs/share/doc/rust/html' to '/home/noone/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html'
error: caused by: permission denied
```

**Comment by JoshOrndorff** [comment]
This come from the rustup command that the script calls. The error is `permission denied`. Are you running this as your normal user account?

**Comment by noahsalvadordenjo** [comment]
administrator

**Comment by JoshOrndorff** [comment]
Are you using Windows? I'm guessing you might be because you mentioned `administrator` account. This script does not support windows. If you are, I recommend using the windows subsystem for linux.

There are also dedicated setup instructions for Windows at https://substrate.dev/docs/en/overview/getting-started#getting-started-on-windows if you can't or don't want to use WSL.

**Comment by noahsalvadordenjo** [comment]
I've installed ubuntu on windows and that worked fine for me in the past
