### ISSUE TITLE
Rococo Slot Request:paraid 4361

### ISSUE THREAD

**Issue by zachary0809** [paritytech/subport#634]
Hello, Magnet has applied for the parachain a few days ago, but it is still parathread until now.Please help us upgrade. Issue is #633 
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/subport/issues/633
```

**Comment by SBalaguer** [comment]
Hey @zachary0809, Rococo has been fully upgraded to the Coretime model, and therefore it does not require you to be forced to a slot anymore. 

In order to get a core, you need to:
- Purchase Bulk Coretime. This has to be done from the Coretime Parachain (you will need to teleport ROC to your account on that chain), executing the extrinsic `broker.purchase` and set a price for it. You can check the floor price by querying `broker.saleInfo`. Once this extrinsic is executed, you will be able to see an event which details the parameters of the core you bought. You can check this on PolkadotJS explorer.
- Assign Bulk Coretime to your paraID. On the Coretime Parachain, execute the extrinsic `broker.assign` to your paraID. The information that you will need to fill here comes mostly for the event from the previous step, plus the paraID of your own parachain.

It's important to note that any account holding ROC tokens can execute this for the paraID; it doesn't need to be a specific account.

**Comment by zachary0809** [comment]
@SBalaguer  Is there any operating documentation?

**Comment by SBalaguer** [comment]
Hey @zachary0809, proper documentation is being prepared, however the steps that I outlined before are the ones that need to be done.

Any particular question about those?

**Comment by zachary0809** [comment]
Hello,@SBalaguer, I've followed the steps you listed, but the parathread still hasn't turned into a parachain.

**Comment by zachary0809** [comment]
![Image_20240215231910](https://github.com/paritytech/subport/assets/139736437/36c41924-5dc0-426f-abbf-bc37b2fc2a2b)
![Image_20240215231920](https://github.com/paritytech/subport/assets/139736437/921fa953-3938-443e-884d-44f3f22aad48)
These two screenshots are the results of my operations on Coretime Parachain

**Comment by SBalaguer** [comment]
Perfect. The reason behind that is that the `begin` of your region is at timeslice `115,350`, and currently Rococo is at timeslice`115,026`. On Rococo each timeslice is composed of 80 blocks ([Ref](https://github.com/paritytech/polkadot-sdk/blob/5fc7622cb312f2d32ec8365012ee0a49622db8c8/cumulus/parachains/runtimes/coretime/coretime-rococo/src/coretime.rs#L228)), meaning that in ~26,000 blocks your task will start getting validated.

<img width="366" alt="image" src="https://github.com/paritytech/subport/assets/10047147/247720bd-7307-4935-a58a-1ae082b46416">

**Comment by zachary0809** [comment]
OK, I know it, thank you
