### ISSUE TITLE
how can I read extrinsic result status as fail or success for an block 

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#74]
hi,

how can I read extrinsic result status as fail or success for an block ?

For example: 

`
```
const signedBlock = await api.rpc.chain.getBlock("0xba2a636cb0649ae2c518e2e7b6fdcdacb731e49929b2ca93ff40604ff88b7d2a")

const exts = signedBlock.block.extrinsics.filter(y=> (y.method.toHuman().method === "transferKeepAlive" && y.method.toHuman().section === "balances"))

exts.forEach(y=>{
console.log(y.toHuman()) //.method.args
})
```
`

// results snippet:

`{
  isSigned: true,
  method: {
    args: [
      '14GK1gnP1Bu2W8JyxUPYA4fJFw3np5963n8hYuEkUVxZ5eTE',
      '30.0000 DOT'
    ],
    method: 'transferKeepAlive',
    section: 'balances'
  },
  era: { MortalEra: { period: '64', phase: '60' } },
  nonce: '1',
  signature: '0x4e3bde7c2a9518a975aeff5992a5b153dc599a5656b1caf80f8dc3b2cf3c6d2a79a4d6f6991a63ef0230079fe4316b44be25bf5d24d751cd7a2e4e856172ff8a',
  signer: '16VLsJ2LJRcdtApZuBiLn2oSNH4JuizLRVQKXEEhDwMWz6yu',
  tip: '0'
}
{
  isSigned: true,
  method: {
    args: [
      '15DiUX8xoaaLGP1bHos4HKuzvyP4PifzpHaYdmdy5WTsU2Tf',
      '4.0000 DOT'
    ],
    method: 'transferKeepAlive',
    section: 'balances'
  },
  era: { MortalEra: { period: '64', phase: '61' } },
  nonce: '12',
  signature: '0x40ce11bd6f3da7eb068bce5e58ef0cabd7d00aed736cb0cef52f03ca79303105c52ea796523d754c611ca5c7c3be9a2d4f352d185df47140875460a9ad1c4288',
  signer: '12T5eadTxvZazyr4sdovK7Luhrdij2gPyBEDs3vu4dZxja6j',
  tip: '0'
}
`

I would like to get only success transfers, but second item  of  result (extrinsic) is fail but snippet has not this status info.

How can I read it?

thank you

**Comment by emostov** [comment]
In order to tell if an extrinsic was successful you will need to look at events associated with the extrinsic. Events are not stored within the block so can either be fetched with an additional query or by using the `api.derive.chain.getBlock` method that polkadot.js exposes (this will do the query under the hood for you).

For the former you will need to query `api.query.system.events.at(hash)`, where hash is the ID for the block you need events for. You will than need to iterate through the events, looking at the phase. Events that are `.isApplyExtrinsic` will have an associated getter `.asApplyExtrinisc` which returns the index of the extrinsic they are associated with. These will give you events associated with extrinsics executed in the block, but not events associated with the `onIntialize` and `onFinialize` hooks that pallets have, which can execute arbitrary code and deposit events. You can then find the extrinsic at that index and group them together in a data type of your choice. Here is an example from substrate-api-sidecar: https://github.com/paritytech/substrate-api-sidecar/blob/c798ada99d020755443c92ea31174a1e00267b37/src/services/blocks/BlocksService.ts#L250-L326

The second way to do it is probably a bit easier and looks like it just got added to polkadot-js; you can use the `api.derive.chain.getBlock` or `api.derive.chain.subscribeNewBlocks` as added in this PR: https://github.com/polkadot-js/api/pull/3020.

**Comment by danforbes** [comment]
@sollover Zeke's answer is almost certainly correct, but just noting that this is really a question about the Polkadot{JS} API, it seems, not really Substrate itself, which is what this repo is intended to support. This may be helpful https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event Please reopen this Issue if you think I've closed it incorrectly.
