### ISSUE TITLE
not able to register parachain in local rococo setup

### ISSUE THREAD

**Issue by marc0olo** [paritytech/subport#90]
Hi,

I followed the [instructions in the cumulus readme](https://github.com/paritytech/cumulus#launch-a-local-setup-including-a-relay-chain-and-a-parachain) and created a docker-compose setup to test it. Unfortunately I cannot register the Parachain using Polkadot-JS Apps.

I get always this error:
![image](https://user-images.githubusercontent.com/8124114/106299486-80592480-6255-11eb-9bfc-cfd6ffc12705.png)

I need to say that I created the `genesis-state` as well as the `genesis-wasm` outside of docker on my local machine (Mac). Could this be the reason?

Would be good to get some help here. Another question I would have is whether it is already possible to perform Parachain slot auctions on the local rococo network. I'd like to test this. Haven't found information about that so far.

Thanks,
Marco

**Comment by NukeManDan** [comment]
This is a simple fix as it turns out! [The API FAQ](https://polkadot.js.org/docs/api/FAQ#the-node-returns-a-could-not-convert-error-on-send) has details about why this occurs.

In this case as the error suggests, you have issues related to the mapping of `MultiAddress`. There is a patch on the way to fix this, for now you need can fix the issue by following [instructions here]()

For the polkadot UI you need to go into settings -> developer and enter this:

```
{
"Address": "MultiAddress",
"LookupSource": "MultiAddress"
}
```
![image](https://user-images.githubusercontent.com/35669742/106317198-30fdfe80-622b-11eb-9fa4-f32b8f822ba0.png)

**Comment by NukeManDan** [comment]
> Would be good to get some help here. Another question I would have is whether it is already possible to perform Parachain slot auctions on the local rococo network. I'd like to test this. Haven't found information about that so far.

Presently the Parity team is bringing on rococo parachains one by one. Join the Rococo chat to get support [here](https://matrix.to/#/!WuksvCDImqYSxvNmua:matrix.parity.io?via=matrix.parity.io)

**Comment by marc0olo** [comment]
Thanks for the quick response! Will test it on monday! 👍 

And I will definitely join the Rococo chat to place my questions there.

**Comment by NukeManDan** [comment]
Looking forward to seeing you there!
